version: '3'

# 1 service = 1 container.
services:
  postgres_db:
    image: 'postgres:11.10-alpine'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
    - ./db-data/:/var/lib/postgresql/data/
    - ./db-postgres:/usr/local/var/postgres
